<h1 style = "color : Brown">Pandas</h1>

- Pandas is fast, powerful, flexible and easy to use open source data analysis and manipulation tool.

- Pandas is a Python library.

- Pandas is used to analyze data.

In [1]:
!pip install -q pandas

In [3]:
import pandas as pd
# it is pandas and not panda

import numpy as np

In [5]:
#df = pd.read_csv('Churn_Modelling.csv')
#df = pd.read_excel('xyz.xlsx', sheet_name = 'Page 1')
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

# df = data frame
# df is used to read the files in various format like CSV, XLS, JSON, TXT etc.
# Only after you create the "df" from the file, you can use pandas methods on that df

In [10]:
df.count()

longitude             17000
latitude              17000
housing_median_age    17000
total_rooms           17000
total_bedrooms        17000
population            17000
households            17000
median_income         17000
median_house_value    17000
dtype: int64

In [7]:
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [ ]:
# df.head() --> shows tables from the beginning
# df.tail() --> shows tables from the end
# by default 5 rows in total including the heading
# df.count() --> will give the total count of individual element

In [11]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [12]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [15]:
df.count()
# gives all the columne headings and total values associated with that heading

df.info()
# gives the quick overview of the tables
# Total entries, Columne, Non null, dtype, size of the file etc.
# For a quick overview of the cell

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [18]:
# Describe the statistical information of the numerical columns
df.describe()

# will skip all the non numerical columns
# give details like count,mean,min,std or 50% percentile ,max, 25/50/75 percentile

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [19]:
# Prints all the columns of the dataframe
# columns can be renamed as per standard.
# Dont use spaces in any name.

df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [31]:
# Transpose
# Transpose ROWS into COLUMNS and COLUMNS into ROW
# can combine multiple methods after each other
# print(df.T)
df.T.head()

,0,1,2,3,4,5,6,7,8,9,...,16990,16991,16992,16993,16994,16995,16996,16997,16998,16999
longitude,-114.31,-114.47,-114.56,-114.57,-114.57,-114.58,-114.58,-114.59,-114.59,-114.60,...,-124.22,-124.23,-124.23,-124.23,-124.25,-124.26,-124.27,-124.30,-124.3,-124.35
latitude,34.19,34.40,33.69,33.64,33.57,33.63,33.61,34.83,33.61,34.83,...,41.73,41.75,40.81,40.54,40.28,40.58,40.69,41.84,41.8,40.54
housing_median_age,15.00,19.00,17.00,14.00,20.00,29.00,25.00,41.00,34.00,46.00,...,28.00,11.00,52.00,52.00,32.00,52.00,36.00,17.00,19.0,52.00
total_rooms,5612.00,7650.00,720.00,1501.00,1454.00,1387.00,2907.00,812.00,4789.00,1497.00,...,3003.00,3159.00,1112.00,2694.00,1430.00,2217.00,2349.00,2677.00,2672.0,1820.00
total_bedrooms,1283.00,1901.00,174.00,337.00,326.00,236.00,680.00,168.00,1175.00,309.00,...,699.00,616.00,209.00,453.00,419.00,394.00,528.00,531.00,552.0,300.00

In [28]:
#Sort your dataframe based on Age
#Soft the specific column

#df.sort_values(by='longitude').head(5)
df.sort_values(by='longitude')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
...,...,...,...,...,...,...,...,...,...
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0

In [33]:
df['housing_median_age']

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [34]:
df.housing_median_age
# df['housing_median_age'] --> This way is better because its a standard way to represent the column.

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [37]:
df['housing_median_age'] = df['housing_median_age'] + 1000
df['housing_median_age']
df['housing_median_age'] = df['housing_median_age'] - 1000
# Can perform operations and change the column values
df['housing_median_age']

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [38]:
df['new_housing_median_age_10+'] = df['housing_median_age'] + 10
df.head(5)
# Can add a new column new_housing_median_age_10+

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,25.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,29.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,27.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,24.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,30.0

In [49]:
df['Random Column'] = 'Good Day'
df['Random_Column'] = 'Null'
df.head(5)
# Can add a new column with some static value

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,25.0,Good Day,Null
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,29.0,Good Day,Null
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,27.0,Good Day,Null
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,24.0,Good Day,Null
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,30.0,Good Day,Null

In [56]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   17000 non-null  float64
 1   latitude                    17000 non-null  float64
 2   housing_median_age          17000 non-null  float64
 3   total_rooms                 17000 non-null  float64
 4   total_bedrooms              17000 non-null  float64
 5   population                  17000 non-null  float64
 6   households                  17000 non-null  float64
 7   median_income               17000 non-null  float64
 8   median_house_value          17000 non-null  float64
 9   new_housing_median_age_10+  17000 non-null  float64
 10  Random Column               17000 non-null  object
 11  Random_Column               17000 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.6+ MB

In [63]:
# How to access your rows
# df[start_row:end_row_excluding]

# Get the last row
df[-2:-1]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
16998,-124.3,41.8,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,29.0,Good Day,Null

In [64]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,25.0,Good Day,Null
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,29.0,Good Day,Null
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,27.0,Good Day,Null
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,24.0,Good Day,Null
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,30.0,Good Day,Null
...,...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,62.0,Good Day,Null
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,46.0,Good Day,Null
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,27.0,Good Day,Null
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,29.0,Good Day,Null
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,62.0,Good Day,Null

In [74]:

df.housing_median_age.min()   # minimum age
df.housing_median_age.max()   # maximum age
new_df = df[df.housing_median_age < 2]

# new_df - A value is trying to be set on a copy of a slice from a DataFrame

# perform operation on DF in a column to find out a specific value
# assign it to new DF
# print new DF

In [80]:
new_df
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 10993 to 13708
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   2 non-null      float64
 1   latitude                    2 non-null      float64
 2   housing_median_age          2 non-null      float64
 3   total_rooms                 2 non-null      float64
 4   total_bedrooms              2 non-null      float64
 5   population                  2 non-null      float64
 6   households                  2 non-null      float64
 7   median_income               2 non-null      float64
 8   median_house_value          2 non-null      float64
 9   new_housing_median_age_10+  2 non-null      float64
 10  Random Column               2 non-null      object
 11  Random_Column               2 non-null      object
dtypes: float64(10), object(2)
memory usage: 208.0+ bytes

In [94]:
new_df
new_df[0:1].housing_median_age

df[0:1].housing_median_age

0    15.0
Name: housing_median_age, dtype: float64

In [96]:
df[df.housing_median_age < 2].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
10993,-120.93,37.65,1.0,2254.0,328.0,402.0,112.0,4.2500,189200.0,11.0,Good Day,Null
13708,-122.00,38.23,1.0,2062.0,343.0,872.0,268.0,5.2636,191300.0,11.0,Good Day,Null

In [98]:
df['Random_Column'].fillna(10)

# To fill the null value
# fill not available value with value within the bracket

0        Null
1        Null
2        Null
3        Null
4        Null
         ...
16995    Null
16996    Null
16997    Null
16998    Null
16999    Null
Name: Random_Column, Length: 17000, dtype: object

In [103]:
new_df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
10993,-120.93,37.65,1.0,2254.0,328.0,402.0,112.0,4.2500,189200.0,11.0,Good Day,Null
13708,-122.00,38.23,1.0,2062.0,343.0,872.0,268.0,5.2636,191300.0,11.0,Good Day,Null

In [106]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 10993 to 13708
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   2 non-null      float64
 1   latitude                    2 non-null      float64
 2   housing_median_age          2 non-null      float64
 3   total_rooms                 2 non-null      float64
 4   total_bedrooms              2 non-null      float64
 5   population                  2 non-null      float64
 6   households                  2 non-null      float64
 7   median_income               2 non-null      float64
 8   median_house_value          2 non-null      float64
 9   new_housing_median_age_10+  2 non-null      float64
 10  Random Column               2 non-null      object
 11  Random_Column               2 non-null      object
dtypes: float64(10), object(2)
memory usage: 208.0+ bytes

In [111]:
#new_df.pop('Random Column')  # Delete the entire column
#new_df.pop('Random_Column')  # Delete the entire column
#new_df.info()                # You need to execute the info to df.columns command to view the available columne
new_df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'new_housing_median_age_10+'],
      dtype='object')

In [112]:
new_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+
10993,-120.93,37.65,1.0,2254.0,328.0,402.0,112.0,4.2500,189200.0,11.0
13708,-122.00,38.23,1.0,2062.0,343.0,872.0,268.0,5.2636,191300.0,11.0

In [116]:
new_df_1 = new_df.drop('new_housing_median_age_10+', axis=1)

# Dropping method to pop the column
# 2 methods pop and drop to remove the column
# assigned it to new DF.

In [118]:
new_df_1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10993,-120.93,37.65,1.0,2254.0,328.0,402.0,112.0,4.2500,189200.0
13708,-122.00,38.23,1.0,2062.0,343.0,872.0,268.0,5.2636,191300.0

In [120]:
df['housing_median_age']

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [121]:
df['housing_median_age'].apply(np.sqrt)

# Apply numpy np.sqrt function on the values of a given column

0        3.872983
1        4.358899
2        4.123106
3        3.741657
4        4.472136
           ...
16995    7.211103
16996    6.000000
16997    4.123106
16998    4.358899
16999    7.211103
Name: housing_median_age, Length: 17000, dtype: float64

In [124]:
df.head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_housing_median_age_10+,Random Column,Random_Column
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,25.0,Good Day,Null
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,29.0,Good Day,Null
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,27.0,Good Day,Null

In [133]:
df['housing_median_age'].apply(np.sqrt)
# # Apply numpy np.sqrt function on the values of a given column
#df = df.drop('new_housing_median_age_10+', axis=1)
#df = df.drop('Random Column', axis=1)
#df = df.drop('Random_Column', axis=1)
df = df.drop('SqRoot_Balance', axis=1)
df.head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,1.402851,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,1.444921,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,1.424971,720.0,174.0,333.0,117.0,1.6509,85700.0

In [135]:
#Drops all the null values in Age column
# dropna means drop not available values or null values from a specific column

df['latitude'].dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [136]:
df.dropna()

# dropna means drop not available values or null values from the whole file

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,1.402851,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,1.444921,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,1.424971,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,1.390804,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,1.454215,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,1.638704,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,1.565085,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,1.424971,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,1.444921,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,1.638704,1820.0,300.0,806.0,270.0,3.0147,94600.0

## Concat & Merging

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                  index=[0,1,2,3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                  index=[4,5,6,7])

In [ ]:
#frames = [df1,df2]

In [ ]:
result = pd.concat([df1, df2])

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

![image.png](attachment:image.png)

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']}, )


df2 = pd.DataFrame({'E': ['A4', 'A5', 'A6', 'A7'],
                    'F': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C0', 'C3', 'C6', 'C7'],
                    'G': ['D4', 'D5', 'D6', 'D7']}, )


merge_df = pd.merge(df1, df2, on='C', how='outer')

In [ ]:
merge_df

     A    B   C    D    E    F    G
0   A0   B0  C0   D0   A4   B4   D4
1   A1   B1  C1   D1  NaN  NaN  NaN
2   A2   B2  C2   D2  NaN  NaN  NaN
3   A3   B3  C3   D3   A5   B5   D5
4  NaN  NaN  C6  NaN   A6   B6   D6
5  NaN  NaN  C7  NaN   A7   B7   D7

## loc vs iloc

The main distinction between the two methods is:

- loc gets rows (and/or columns) with particular labels.

- iloc gets rows (and/or columns) at integer locations.

In [ ]:
s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [ ]:
s.loc[0]    # value at index label 0

'd'

In [ ]:
s.iloc[0]   # value at index location 0

'a'

In [ ]:
s.loc[0:1]  # rows at index labels between 0 and 1 (inclusive)

0    d
1    e
dtype: object

In [ ]:
s.iloc[0:1] # rows at index location between 0 and 1 (exclusive)

49    a
dtype: object

### What if you sort the Series

In [ ]:
s = s.sort_index()

In [ ]:
s

0     d
1     e
2     f
47    c
48    b
49    a
dtype: object

In [ ]:
s.iloc[0]

'd'

In [ ]:
s.loc[0]    # value at index label 0

'd'

In [ ]:
s.iloc[0]   # value at index location 0

'd'

In [ ]:
s.loc[0:1]  # rows at index labels between 0 and 1 (inclusive)

0    d
1    e
dtype: object

In [ ]:
s.iloc[0:1] # rows at index location between 0 and 1 (exclusive)

0    d
dtype: object

![image.png](attachment:image.png)